# Generated by Django 4.1.3 on 2022-11-28 14:48

import random

from django.db import migrations
from mimesis import Person, Finance, Address


class Migration(migrations.Migration):

    def fake_create_factory(apps, schema_editor):
        Element = apps.get_model('electronicsSales', 'Element')
        Country = apps.get_model('electronicsSales', 'Country')
        City = apps.get_model('electronicsSales', 'City')

        person = Person()
        fin = Finance()
        address = Address()
        for i in range(5):
            Element.objects.bulk_create(
                [
                    Element(
                        name=fin.company(),
                        country=Country.objects.get(id=random.randint(1, 60)),
                        city=City.objects.get(id=random.randint(1, 100)),
                        street=address.street_name(),
                        house=address.street_number(),
                        email=person.email(),
                        debt=random.randint(1, 1000),
                    ),
                ]
            )


    dependencies = [
        ('electronicsSales', '0004_add_products'),
    ]

    operations = [
        migrations.RunPython(fake_create_factory),

    ]
