# Generated by Django 4.1.3 on 2022-11-28 14:48

import random

from django.db import migrations
from mimesis import Person, Finance, Address


class Migration(migrations.Migration):

    def fake_add_products_to_factory(apps, schema_editor):
        Element = apps.get_model('electronicsSales', 'Element')
        Product = apps.get_model('electronicsSales', 'Product')

        elements = Element.objects.all()
        for el in elements:
            for i in range(1, 5):
                try:
                    el.products.add(Product.objects.get(id=random.randint(1, 30)))
                except:
                    print('продукт повторяется')


    dependencies = [
        ('electronicsSales', '0005_add_factory'),
    ]

    operations = [
        migrations.RunPython(fake_add_products_to_factory),

    ]
